#
# HAL
# continuous integration (ci) pipeline
#

# see Globals.py for documentation on environment variable settings

name: "CI Pipeline"
on: push
env:
  REAL_TIME: "False"
  HEADLESS: "True"
  MLFLOW_TRACKING_URI: "http://aigmlflow.mrzzy.co"
  AWS_DEFAULT_REGION: "ap-southeast-1"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
  lint:
    runs-on: ubuntu-20.04
    name: "Lint HAL source code"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: "Install dependencies"
        run: |
          make deps
      - name: "Lint bentobox-sdk"
        run: |
          make lint
    
  # Recorded Playtests runs one game of HAL with metrics collection and video camera,
  # metrics & recording are uploaded to the AIG MLFlow server in the `np-aig-records' experiment.
  recorded-playtest-easy:
    runs-on: ubuntu-20.04
    name: "Recorded Playtest vs Easy AI"
    env:
      DIFFICULTY: "easy"
      TEAM_NAME: "You,EasyAI"
      LOGGER: "MLFlowLogger"
      CAMERA: "OpenCVCamera"
      MLFLOW_EXPERIMENT: "np-aig-records"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: "Install dependencies"
        run: |
          make deps
      - name: "Playtest against EasyAI"
        run: |
          make run

  recorded-playtest-hard:
    runs-on: ubuntu-20.04
    name: "Recorded Playtest vs Hard AI"
    env:
      DIFFICULTY: "hard"
      TEAM_NAME: "You,HardAI"
      LOGGER: "MLFlowLogger"
      CAMERA: "OpenCVCamera"
      MLFLOW_EXPERIMENT: "np-aig-records"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: "Install dependencies"
        run: |
          make deps
      - name: "Playtest against HardAI"
        run: |
          make run

  recorded-playtest-master:
    runs-on: ubuntu-20.04
    name: "Recorded Playtest vs Master"
    env:
      TEAM_NAME: "You,Master"
      LOGGER: "MLFlowLogger"
      CAMERA: "OpenCVCamera"
      MLFLOW_EXPERIMENT: "np-aig-records"
      NPC_BLUE_SRCS: "master/Knight_TeamA.py,master/Archer_TeamA.py,master/Wizard_TeamA.py"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          ref: "master"
          path: "master"
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: "Install dependencies"
        run: |
          make deps
      - name: "Playtest against Master"
        run: |
          make run

  # Multi Trial Playtest runs multiple games of HAL with basic metrics collection
  # aggregates the results of multiple matches to given more accurate verdict on 
  # which AI is better.
  trials-playtest-easy:
    runs-on: ubuntu-20.04
    name: "Multiple Trial Playtest vs Easy AI"
    env:
      DIFFICULTY: "easy"
      TEAM_NAME: "You,EasyAI"
      MLFLOW_EXPERIMENT: "np-aig-trials"
      RED_WIN_NONZERO_STATUS: "True"
      N_TRIALS: 31
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: "Install dependencies"
        run: |
          make deps
      - name: "Playtest against EasyAI"
        run: |
          make run-trials

  trials-playtest-hard:
    runs-on: ubuntu-20.04
    name: "Multiple Trial Playtest vs Hard AI"
    env:
      DIFFICULTY: "hard"
      TEAM_NAME: "You,HardAI"
      MLFLOW_EXPERIMENT: "np-aig-trials"
      RED_WIN_NONZERO_STATUS: "True"
      N_TRIALS: 31
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: "Install dependencies"
        run: |
          make deps
      - name: "Playtest against HardAI"
        run: |
          make run-trials

  trials-playtest-master:
    runs-on: ubuntu-20.04
    name: "Multiple Trial Playtest vs Master"
    env:
      TEAM_NAME: "You,Master"
      MLFLOW_EXPERIMENT: "np-aig-trials"
      RED_WIN_NONZERO_STATUS: "True"
      NPC_BLUE_SRCS: "master/Knight_TeamA.py,master/Archer_TeamA.py,master/Wizard_TeamA.py"
      N_TRIALS: 31
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          ref: "master"
          path: "master"
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: "Install dependencies"
        run: |
          make deps
      - name: "Playtest against Master"
        run: |
          make run-trials

