#
# HAL
# continuous integration (ci) pipeline
# for pull requests
#

# see Globals.py for documentation on environment variable settings

name: "CI Pipeline (Pull Request)"
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
env:
  REAL_TIME: "False"
  HEADLESS: "True"
  MLFLOW_TRACKING_URI: "http://aigmlflow.mrzzy.co"
  AWS_DEFAULT_REGION: "ap-southeast-1"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
  lint:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'ok-to-test') || github.event.label.name == 'ok-to-test' }}
    runs-on: ubuntu-20.04
    name: "Lint HAL source code"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: "Install dependencies"
        run: |
          make deps
      - name: "Lint bentobox-sdk"
        run: |
          make lint

  recorded-playtest-master:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'ok-to-test') || github.event.label.name == 'ok-to-test' }}
    runs-on: ubuntu-20.04
    name: "Recorded Playtest vs Master"
    env:
      TEAM_NAME: "You,Master"
      LOGGER: "MLFlowLogger"
      CAMERA: "OpenCVCamera"
      MLFLOW_EXPERIMENT: "np-aig-records"
      NPC_BLUE_SRCS: "master/Knight_TeamA.py,master/Archer_TeamA.py,master/Wizard_TeamA.py"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          ref: "master"
          path: "master"
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: "Install dependencies"
        run: |
          make deps
      - name: "Playtest against Master"
        run: |
          make run

  trials-playtest-master:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'ok-to-test') || github.event.label.name == 'ok-to-test' }}
    runs-on: ubuntu-20.04
    name: "Multiple Trial Playtest vs Master"
    env:
      TEAM_NAME: "You,Master"
      MLFLOW_EXPERIMENT: "np-aig-trials"
      RED_SIG_BETTER_NONZERO_STATUS: "True"
      NPC_RED_SRCS: "master/Knight_TeamA.py,master/Archer_TeamA.py,master/Wizard_TeamA.py"
      N_TRIALS: 41
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          ref: "master"
          path: "master"
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: "Install dependencies"
        run: |
          make deps
      - name: "Playtest against Master"
        run: |
          make run-trials

